services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-engineer:latest
    container_name: laravel-engineer-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    # user: "${UID:-1000}:${GID:-1000}"  # Comentado para permitir root
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=database
    depends_on:
      - redis

  # Worker para processar jobs/queues
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-engineer-worker
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    # user: "${UID:-1000}:${GID:-1000}"  # Comentado para permitir root
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - laravel-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=database
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    depends_on:
      - app

  # Redis para cache e sessões (opcional, mas recomendado)
  redis:
    image: redis:7-alpine
    container_name: laravel-engineer-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-network

  # MailHog para testes de email
  mailhog:
    image: mailhog/mailhog:latest
    container_name: laravel-engineer-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
